service: serverless-lambda-aws

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: ap-southeast-1

functions:
  hello:
    handler: src/handler.generateRandomNumber
    timeout: 60 #seconds
    memorySize: 128 #Mb
